### ISSUE TITLE
Presenter with Pagination not work as expected

### ISSUE THREAD

**Issue by fuzzdis** [davidhemphill/presenter#13]
The great pr #7 introduced the presentTransformed marcos to let the presenter work with Pagination.

But due to my experiment, if I chain the paginate marco and presenter marco within the eloquent model, the presenter is actually return a Collection object instead of a LengthAwarePaginator object.

Code simple:
City::orderBy('city_id')->paginate()->presentTransformed(CityPresenter::class); => Collection 
City::orderBy('city_id')->paginate(); => LengthAwarePaginator 

Env:
php 5.6, presenter 1.0.4, laravel 5.4.36

**Comment by robinmalburn** [comment]
That's because the transform macro is chainable (like the native `Collection::transform` method), so it always returns the current collection.  In your example, if you put the result of `City::orderBy('city_id')->paginate()` in to its own variable and then separately call `->presentTransformed(CityPresenter::class)` on that, you should get the expected result.  So, for example:

```php

// This gets the an instance of LengthAwarePaginator.
$cities = City::orderBy('city_id')->paginate();

// This runs the transform macro which modifies the paginator's internal collection in place, 
// wrapping the models as presenters, whilst leaving $cities as still being an instance of 
// LengthAwarePaginator.
$cities->presentTransformed(CityPresenter::class) 
```

So, using this you could chain applying multiple presenters, e.g `$cities->presentTransformed(CityPresenter::class)->presentTransformed(OtherPresenter::class)`.  These would both modify the underlying collection, whilst leaving `$cities` as an instance of `LengthAwarePaginator`

**Comment by fuzzdis** [comment]
Thanks, it works.
